### ISSUE TITLE
test_data.py fixtures are executed multiple times

### ISSUE THREAD

**Issue by AnelMusic** [GokuMohandas/MLOps#10]
In MLOps/tests/tagifai/test_data.py:

The two fixtures:

@pytest.fixture
def tags():
 ...
@pytest.fixture
def df():
 ...
are executed multiple times (for every test that uses df or tags).
In your context this is not a big deal as there is no real resource consumption, however, you can set the scope to module to make sure your fixtures are called only once.

@pytest.fixture(scope = 'module')
def tags():

@pytest.fixture(scope = 'module')
def df():

**Comment by GokuMohandas** [comment]
Great catch @AnelMusic! I'll update it with this fix.
