### ISSUE TITLE
Conflicting directory for config.py

### ISSUE THREAD

**Issue by oskarryn** [GokuMohandas/MLOps#14]
The file config.py is in the app directory, which is consisted with the "Directory structure" described in the readme.
At the same time, the first line of config.py indicates that the file should be in the tagifai directory (`# tagifai/config.py`). Also, looking at the first code snippet in the Testing->Data section, there's `from tagifai import config`. Finally, the snippet in Scripting->Organization->Organizing->Operations has `from config import config`.

**Comment by GokuMohandas** [comment]
Hey everyone, I made quite a few changes to this repo since last year so let me know if you're still facing these issues.
