### ISSUE TITLE
venv using python3 -m venv venv issue

### ISSUE THREAD

**Issue by peeyushpashine** [GokuMohandas/MLOps#15]
venv using "python3 -m venv venv" creates python version based on python version of host system. e.g.
if I have conda env py36 which uses python 3.6 and running "Makefile venv" will install venv of python 3.6 but if  I have conda env py37 which uses python 3.7 and running "Makefile venv" will install venv of python 3.7. Here python_requires in setup.py isn't having an impact on venv version.

**Comment by tcmle** [comment]
got similar issue, while using default pyton 3.9, the  make venv command keep having errors

**Comment by kumar-abhishek** [comment]
Running into lots of similar issues. Do we have a solution?

**Comment by GokuMohandas** [comment]
hey everyone, I made a lot of updates to this recently so let me know if you're still facing issues. And if something in the makefile is not compatible with your system, feel free to use the commands directly with bash/zsh.
