### ISSUE TITLE
pip install error from guide

### ISSUE THREAD

**Issue by hieucnguyen** [GokuMohandas/MLOps#9]
Hi Goku, when I use your method of creating a new virtual environment and run:
```
python -m pip install -e ".[dev]" --no-cache-dir
```
I get an error of **"ModuleNotFoundError: No module named 'Cython'"**. 
- Tried again with pipenv and still fails. 
- The only way I can install the requirements are using poetry, and deleting all dependency specific versions (as followed [here](https://stackoverflow.com/a/64672646)). But even using poetry, the numpy and snorkel packages cannot be installed.
- After using poetry and generate the requirements.txt again, then pip install -r requirements.txt now works (Without snorkel)

More info: Poetry dependency resolution in pyproject.toml:

```
[tool.poetry.dependencies]
python = "^3.8"
apache-airflow = "^2.1.0"
airflow-provider-great-expectations = "^0.0.6"
dvc = "^2.3.0"
fastapi = "^0.65.2"
feast = "^0.10.7"
matplotlib = "^3.4.2"
mlflow = "^1.17.0"
nltk = "^3.6.2"
numpyencoder = "^0.3.0"
optuna = "^2.8.0"
pandas = "^1.2.4"
pretty-errors = "^1.2.21"
rich = "^10.3.0"
scikit-multilearn = "^0.2.0"
seaborn = "^0.11.1"
sklearn = "^0.0"
streamlit = "^0.82.0"
torch = "^1.9.0"
typer = "^0.3.2"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
watchdog = "^2.1.2"
wordcloud = "^1.8.1"
great-expectations = "^0.13.19"
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = "^21.6b0"
flake8 = "^3.9.2"
isort = "^5.8.0"
jupyterlab = "^3.0.16"
pre-commit = "^2.13.0"
mkdocs-macros-plugin = "^0.5.5"
mkdocs-material = "^7.1.8"
mkdocstrings = "^0.15.2"

[tool.poetry.dev-dependencies]
```

**Comment by GokuMohandas** [comment]
Hmm I tried to reproduce this inside an empty docker container and didn't run into this issue. It might be because of a cython dependency? which should be resolvable using pip3 install --upgrade cython.
